name: verify

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: oj-verify all

    - name: Create snippet and template files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git checkout master && python3 vim/src/main.py

    - name: Create LeTeX file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git checkout master && python3 tex/src/main.py

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@master
      with:
        root_file: main.tex
        working_directory: tex/
        args: "-e '$latex=platex;$pdf_mode=3;'"


    - name: Upload PDF
      uses: actions/upload-artifact@master
      with:
        name: tex
        path: tex
      if: always()
